[colourSchemes.synthwaveSunrise]
name = "Synthwave Sunrise"

windowsTerminalTheme = "light"

success = "green"
error = "red"

accentOne = "purple"
accentOneBright = "brightPurple"
accentOneForeground = "background"

accentTwo = "cyan"
accentTwoBright = "brightCyan"
accentTwoForeground = "background"
accentTwoError = "brightRed"
accentTwoSuccess = "brightGreen"

accentThree = "yellow"
accentThreeBright = "yellow"
accentThreeForeground = "background"

accentFour = "blue"
accentFourBright = "brightBlue"
accentFourForeground = "background"

black = "#000000"
brightBlack = "#555753"
blue = "#5900B8"
brightBlue = "#8C1EFF"
cyan = "#00A5A5"
brightCyan = "#00E0E0"
green = "#73A800"
brightGreen = "#CCFF00"
purple = "#B000BD"
brightPurple = "#F222FF"
red = "#C20044"
brightRed = "#FF2975"
white = "#D3D7CF"
brightWhite = "#E0E0E0"
yellow = "#FDAF40"
brightYellow = "#FDF200"

background = "#FFFFFF"
foreground = "#555753"

cursorColor = "#000000"
selectionBackground = "#FFFFFF"
